import React from 'react';
export interface PictogramList {
    icon: 'AstronautFishing' | 'AstronautFlight' | 'AstronautHello' | 'AstronautSittingOnPlanet' | 'AstronautWave' | 'AstronautWithFlag' | 'EssentialsAccept' | 'EssentialsAdd' | 'EssentialsAirplane' | 'EssentialsBattery' | 'EssentialsCalendar' | 'EssentialsClock' | 'EssentialsCode' | 'EssentialsCompass' | 'EssentialsDecline' | 'EssentialsDiamond' | 'EssentialsEarth' | 'EssentialsHide' | 'EssentialsHome' | 'EssentialsLightbulb' | 'EssentialsLock' | 'EssentialsNetwork' | 'EssentialsNotification' | 'EssentialsPowerButton' | 'EssentialsProfile' | 'EssentialsRefresh' | 'EssentialsRemove' | 'EssentialsSecurity' | 'EssentialsShow' | 'EssentialsStyleCode' | 'EssentialsTools' | 'EssentialsWaiting' | 'EssentialsWarning' | 'EssentialsWriteMessage' | 'EssentialsWrite' | 'FileApprove' | 'FileDelete' | 'FileEdit' | 'FileLoading' | 'FileLock' | 'FileOptions' | 'FileSearch' | 'FileUnlock' | 'FinanceAnalysis' | 'FinanceBankCheque' | 'FinanceCashAnalysis' | 'FinanceCreditCard' | 'FinanceGlobalCurrency' | 'FinanceGlobalFunding' | 'FinanceInvestmentBanking' | 'FinanceInvoice' | 'FinanceMoneyAnalysis' | 'FinanceMoneyBag' | 'FinanceMoneyGrowthAnalysis' | 'FinanceMoneyGrowthGraph' | 'FinanceMoneyGrowthTrend' | 'FinanceMoneyGrowth' | 'FinancePercentageInvestment' | 'FinancePiggyBank' | 'FinanceSafeInvestment' | 'FinanceSearchingForCash' | 'FinanceSecurity' | 'FinanceTimeIsMoney' | 'FinanceWallet' | 'FolderApprove' | 'FolderDelete' | 'FolderEdit' | 'FolderLoading' | 'FolderLock' | 'FolderOptions' | 'FolderSearch' | 'FolderUnlock' | 'Wireless404' | 'WirelessAchievement' | 'WirelessBrowserSearch' | 'WirelessBug' | 'WirelessCloud' | 'WirelessDownloadFiles' | 'WirelessDownload' | 'WirelessEmail' | 'WirelessEnergy' | 'WirelessGlobal' | 'WirelessHistory' | 'WirelessInternet' | 'WirelessLoading' | 'WirelessLocked' | 'WirelessMark' | 'WirelessPassword' | 'WirelessPrinter' | 'WirelessProtected' | 'WirelessReceiving' | 'WirelessSave' | 'WirelessSearchResults' | 'WirelessSearch' | 'WirelessSecured' | 'WirelessSending' | 'WirelessSettings' | 'WirelessTimedOut' | 'WirelessUnavailable' | 'WirelessUnlocked' | 'WirelessView' | 'WirelessWaiting' | 'WirelessWireless' | 'WirelessWorldConnection';
}
interface Props extends PictogramList {
    alt?: string;
    className?: string;
    [x: string]: any;
}
declare const Pictogram: React.FC<Props>;
export default Pictogram;
